version: "3"
services:
  web:
    container_name: website
    build: .
    command: sh -c 'npm install && npm run dev'
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000

  backend:
    build: ./node
    command: npm start
    volumes:
      - ./node/app:/usr/app/
      - ./resources:/usr/app/resources
      - /usr/app/node_modules
    ports:
      - "3050:3050"
